### ISSUE TITLE
Default Settings don't move to new Application version while updating

### ISSUE THREAD

**Issue by martinboy** [vkravets/FileTemplatesVariable#10]
Don't know is it a part of plugin implementation or Idea platform but plugin options from PhpStorm's Default Settings don't move to the new version. Reproduced it while upgrading from 7.x to 8.x.

It is not a big problem, because I can manualy copy project.default.xml file to the new application version though

**Comment by vkravets** [comment]
Hmmm... I will check this, thanks for the report!

**Comment by vkravets** [comment]
Let me know if it still reproduce
