### ISSUE TITLE
Default Settings don't apply for newly created project

### ISSUE THREAD

**Issue by martinboy** [vkravets/FileTemplatesVariable#11]
Steps to reproduce:
1. Assign Default  Settings for plugin in File > Default Settings...
2. Create New project
3. Go to PhpStorm > Preferences... > Other Settings > File and Code Template Variables
The list of variable is empty.

Perhaps it is the part of incompatibility with the new Setting interface in PhpStorm 8.x

Reproduced on PhpStorm 8.0.2 on OS X 10.9.5

**Comment by vkravets** [comment]
I will try to check this... Thanks for the report!
