### ISSUE TITLE
Variables aren't picked up when generating PHPDoc Blocks.

### ISSUE THREAD

**Issue by jaspernbrouwer** [vkravets/FileTemplatesVariable#3]
I've added some variables which I use in the "Includes" tab under "File and Code Templates". Some of these Includes are used are used in "Templates".

An example is the Template `PHP Class`, which uses the includes `PHP File Header` and `PHP Class Doc Comment`, which in turn contain some custom variables.

When I create a new "PHP Class", all variables are filled in correctly.

But when I have an existing file and generate the PHPDoc Block for a class, the variables are _not_ filled in.

Am I expecting to much here? Or is it indeed a bug?

**Comment by denisvmedia** [comment]
Is it still not possible to do?

**Comment by JDGrimes** [comment]
> Is it still not possible to do?

Yes, this is still true. I created an issue to fix this in PhpStorm: https://youtrack.jetbrains.com/issue/WI-33656
